# Generated by Django 3.2.20 on 2023-10-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebUiAutoTest', '0003_auto_20230924_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontpostmanager',
            options={'verbose_name': '前置条件管理', 'verbose_name_plural': '前置条件管理'},
        ),
        migrations.AlterModelOptions(
            name='frontpoststep',
            options={'ordering': ('order',), 'verbose_name': '前置用例', 'verbose_name_plural': '前置用例'},
        ),
        migrations.AlterField(
            model_name='frontpoststep',
            name='FrontPostManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebUiAutoTest.frontpostmanager', verbose_name='前置条件'),
        ),
        migrations.AlterField(
            model_name='webcase',
            name='FrontPostManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebUiAutoTest.frontpostmanager', verbose_name='前置用例步骤'),
        ),
    ]
