# Generated by Django 3.2.20 on 2023-10-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUiAutoTest', '0004_auto_20231005_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleniumhubserver',
            name='serverAddress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='服务器地址'),
        ),
        migrations.AlterField(
            model_name='seleniumhubserver',
            name='serverPort',
            field=models.IntegerField(blank=True, null=True, verbose_name='端口'),
        ),
    ]
