# Generated by Django 3.2.20 on 2023-11-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUiAutoTest', '0005_auto_20231021_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcasestep',
            name='order',
            field=models.IntegerField(default=1, error_messages={'unique': '测试步骤序号不连续。'}, verbose_name='步骤'),
        ),
    ]
