# Generated by Django 3.2.20 on 2023-09-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUiAtuoTest', '0002_webcase_created_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casecontext',
            options={'verbose_name': '上下文参数定义', 'verbose_name_plural': '上下文参数定义'},
        ),
        migrations.AlterModelOptions(
            name='ddtdata',
            options={'verbose_name': '数据驱动', 'verbose_name_plural': '数据驱动'},
        ),
        migrations.AlterModelOptions(
            name='ddtparams',
            options={'verbose_name': '数据驱动数据项', 'verbose_name_plural': '数据驱动数据项'},
        ),
        migrations.AlterModelOptions(
            name='frontpostmanager',
            options={'verbose_name': '前/后置条件管理', 'verbose_name_plural': '前/后置条件管理'},
        ),
        migrations.AlterModelOptions(
            name='frontpoststep',
            options={'ordering': ('order',), 'verbose_name': '前/后置用例', 'verbose_name_plural': '前/后置用例'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '项目管理', 'verbose_name_plural': '项目管理'},
        ),
        migrations.AlterModelOptions(
            name='seleniumhubserver',
            options={'verbose_name': 'SeleniumHub管理', 'verbose_name_plural': 'SeleniumHub管理'},
        ),
        migrations.AlterModelOptions(
            name='webcase',
            options={'verbose_name': 'Web测试用例', 'verbose_name_plural': 'Web测试用例'},
        ),
        migrations.AlterModelOptions(
            name='webcasestep',
            options={'ordering': ('order',), 'verbose_name': '测试步骤', 'verbose_name_plural': '测试步骤'},
        ),
        migrations.AlterField(
            model_name='frontpoststep',
            name='command',
            field=models.CharField(choices=[('open', '打开'), ('send_keys', '输入'), ('clear', '清空'), ('click', '点击'), ('submit', '提交'), ('close', '关闭'), ('double_click', '双击'), ('drag_and_drop_to_object', '拖拽到对象'), ('execute_script', '执行脚本'), ('execute_async_script', '执行异步脚本'), ('mouse_over', '鼠标悬停'), ('pause', '等待'), ('select', '选择'), ('select_frame', '选择frame'), ('switch_to_parent_frame', '返回上级frame'), ('select_window', '选择窗口'), ('store', '存储'), ('store_text', '存储文本'), ('store_title', '存储标题'), ('store_value', '存储值'), ('store_xpath_count', '存储xpath总数'), ('add_cookie', '添加cookie'), ('wait_for_element_not_visible', '等待元素不可见'), ('wait_for_element_present', '待待元素发送'), ('wait_for_element_visible', '等待元素可见'), ('assert_variable', '断言变量'), ('assert_title_is', '断言标题是'), ('assert_title_contains', 'assert_title_包含'), ('assert_url_contains', 'assert_url_包含'), ('assert_url_matches', 'assert_url_匹配'), ('assert_url_to_be', 'assert_url_to_be'), ('assert_url_changes', 'assert_url_变化'), ('assert_presence_of_element_located', 'assert_presence_of_element_located'), ('assert_presence_of_all_elements_located', 'assert_presence_of_all_elements_located'), ('assert_visibility_of_element_located', 'assert_visibility_of_element_located'), ('assert_invisibility_of_element_located', 'assert_invisibility_of_element_located'), ('assert_invisibility_of_element', 'assert_invisibility_of_element'), ('assert_visibility_of', 'assert_visibility_of'), ('assert_visibility_of_any_elements_located', 'assert_visibility_of_any_elements_located'), ('assert_visibility_of_all_elements_located', 'assert_visibility_of_all_elements_located'), ('assert_element_to_be_clickable', 'assert_element_to_be_clickable'), ('assert_staleness_of', 'assert_staleness_of'), ('assert_text_to_be_present_in_element', 'assert_text_to_be_present_in_element'), ('assert_text_to_be_present_in_element_value', 'assert_text_to_be_present_in_element_value'), ('assert_frame_to_be_available_and_switch_to_it', 'assert_frame_to_be_available_and_switch_to_it'), ('assert_element_to_be_selected', 'assert_element_to_be_selected'), ('assert_element_located_to_be_selected', 'assert_element_located_to_be_selected'), ('assert_element_located_selection_state_to_be', 'assert_element_located_selection_state_to_be'), ('assert_number_of_windows_to_be', 'assert_number_of_windows_to_be'), ('assert_alert_is_present', 'assert_alert_is_present'), ('assert_text_of_alert', 'assert_text_of_alert')], max_length=255, verbose_name='操作关键字'),
        ),
        migrations.AlterField(
            model_name='frontpoststep',
            name='order',
            field=models.IntegerField(default=1, verbose_name='步骤'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='command',
            field=models.CharField(choices=[('open', '打开'), ('send_keys', '输入'), ('clear', '清空'), ('click', '点击'), ('submit', '提交'), ('close', '关闭'), ('double_click', '双击'), ('drag_and_drop_to_object', '拖拽到对象'), ('execute_script', '执行脚本'), ('execute_async_script', '执行异步脚本'), ('mouse_over', '鼠标悬停'), ('pause', '等待'), ('select', '选择'), ('select_frame', '选择frame'), ('switch_to_parent_frame', '返回上级frame'), ('select_window', '选择窗口'), ('store', '存储'), ('store_text', '存储文本'), ('store_title', '存储标题'), ('store_value', '存储值'), ('store_xpath_count', '存储xpath总数'), ('add_cookie', '添加cookie'), ('wait_for_element_not_visible', '等待元素不可见'), ('wait_for_element_present', '待待元素发送'), ('wait_for_element_visible', '等待元素可见'), ('assert_variable', '断言变量'), ('assert_title_is', '断言标题是'), ('assert_title_contains', 'assert_title_包含'), ('assert_url_contains', 'assert_url_包含'), ('assert_url_matches', 'assert_url_匹配'), ('assert_url_to_be', 'assert_url_to_be'), ('assert_url_changes', 'assert_url_变化'), ('assert_presence_of_element_located', 'assert_presence_of_element_located'), ('assert_presence_of_all_elements_located', 'assert_presence_of_all_elements_located'), ('assert_visibility_of_element_located', 'assert_visibility_of_element_located'), ('assert_invisibility_of_element_located', 'assert_invisibility_of_element_located'), ('assert_invisibility_of_element', 'assert_invisibility_of_element'), ('assert_visibility_of', 'assert_visibility_of'), ('assert_visibility_of_any_elements_located', 'assert_visibility_of_any_elements_located'), ('assert_visibility_of_all_elements_located', 'assert_visibility_of_all_elements_located'), ('assert_element_to_be_clickable', 'assert_element_to_be_clickable'), ('assert_staleness_of', 'assert_staleness_of'), ('assert_text_to_be_present_in_element', 'assert_text_to_be_present_in_element'), ('assert_text_to_be_present_in_element_value', 'assert_text_to_be_present_in_element_value'), ('assert_frame_to_be_available_and_switch_to_it', 'assert_frame_to_be_available_and_switch_to_it'), ('assert_element_to_be_selected', 'assert_element_to_be_selected'), ('assert_element_located_to_be_selected', 'assert_element_located_to_be_selected'), ('assert_element_located_selection_state_to_be', 'assert_element_located_selection_state_to_be'), ('assert_number_of_windows_to_be', 'assert_number_of_windows_to_be'), ('assert_alert_is_present', 'assert_alert_is_present'), ('assert_text_of_alert', 'assert_text_of_alert')], max_length=255, verbose_name='操作关键字'),
        ),
        migrations.AlterField(
            model_name='webcasestep',
            name='order',
            field=models.IntegerField(default=1, verbose_name='步骤'),
        ),
    ]
