# Generated by Django 3.2.20 on 2023-11-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUiAtuoTest', '0008_alter_webcasestep_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcasestep',
            name='order',
            field=models.IntegerField(default=1, error_messages={'unique': '测试步骤序号不连续。'}, verbose_name='步骤'),
        ),
    ]
