# Generated by Django 3.2.23 on 2023-11-10 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebUiAtuoTest', '0009_alter_webcasestep_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpostmanager',
            name='Product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='WebUiAtuoTest.product', verbose_name='项目名称'),
            preserve_default=False,
        ),
    ]
