# Generated by Django 3.2.23 on 2023-11-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebUiAtuoTest', '0010_frontpostmanager_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontpostmanager',
            name='Product',
        ),
        migrations.AlterField(
            model_name='frontpostmanager',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称+项目'),
        ),
    ]
